---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  "/api/v1/all_cars":
    get:
      summary: all_cars car
      tags:
      - Cars
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    cost:
                      type: integer
                    description:
                      type: text
                    image_url:
                      type: string
                    owner:
                      type: integer
                  required:
                  - "./spec/requests/api/v1/cars_spec.rb[1:1:1:1]"
                  - RSpec::ExampleGroups::ApiV1Cars::ApiV1AllCars::Get::Successful
                  - successful
  "/api/v1/signup":
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                username:
                  type: string
              required:
              - first_name
              - last_name
              - username
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
